### ISSUE TITLE
No monitors on Display settings

### ISSUE THREAD

**Issue by nanogennari** [jthomaschewski/i3-cinnamon#3] opened 2023-03-29 15:04 UTC
On Linux Mint 21.1 (cinnamon 5.6.8) i have no monitors on the display settings:

![image](https://user-images.githubusercontent.com/1216281/228582901-da3ba091-cb59-480b-b394-42a52568e76b.png)

xrandr sill works, but i connect this notebook to different screen configurations a few times an week, using xrandr is very inconvenient. 

On a cinnamon session everything works normally, the problem only occur in the i3-cinnamon session.

Any suggestion on how could i debug this?

inxi -Fxxxrz :
```
System:
  Kernel: 5.15.0-69-generic x86_64 bits: 64 compiler: gcc v: 11.3.0
    Desktop: Cinnamon 5.6.8 tk: GTK 3.24.33 info: i3bar wm: i3 4.20.1 vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: Dell product: Inspiron 7577 v: N/A
    serial: <superuser required> Chassis: type: 10 serial: <superuser required>
  Mobo: Dell model: 0J8HMF v: A00 serial: <superuser required> UEFI: Dell
    v: 1.4.2 date: 01/25/2018
Battery:
  ID-1: BAT0 charge: 18.4 Wh (100.0%) condition: 18.4/55.9 Wh (33.0%)
    volts: 16.9 min: 15.2 model: Samsung SDI DELL J9NH268 type: Li-ion
    serial: <filter> status: Full
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master 3
    serial: <filter> charge: 55% (should be ignored) rechargeable: yes
    status: Discharging
CPU:
  Info: quad core model: Intel Core i7-7700HQ bits: 64 type: MT MCP
    smt: enabled arch: Kaby Lake rev: 9 cache: L1: 256 KiB L2: 1024 KiB
    L3: 6 MiB
  Speed (MHz): avg: 800 high: 802 min/max: 800/3800 cores: 1: 800 2: 800
    3: 800 4: 800 5: 802 6: 800 7: 800 8: 800 bogomips: 44798
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel HD Graphics 630 vendor: Dell driver: i915 v: kernel ports:
    active: DP-1,eDP-1 empty: DP-2, DP-3, HDMI-A-1, HDMI-A-2, HDMI-A-3
    bus-ID: 00:02.0 chip-ID: 8086:591b class-ID: 0300
  Device-2: NVIDIA GP106M [GeForce GTX 1060 Mobile] vendor: Dell
    driver: nvidia v: 525.89.02 pcie: speed: 2.5 GT/s lanes: 16 ports:
    active: none empty: HDMI-A-4 bus-ID: 01:00.0 chip-ID: 10de:1c20
    class-ID: 0300
  Device-3: Microdia Integrated_Webcam_HD type: USB driver: uvcvideo
    bus-ID: 1-12:6 chip-ID: 0c45:6718 class-ID: 0e02
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3200x2048 s-dpi: 96 s-size: 846x541mm (33.3x21.3")
    s-diag: 1004mm (39.5")
  Monitor-1: DP-1 pos: right model: Dell TYPE-C serial: <filter>
    res: 1280x2048 hz: 60 dpi: 93 size: 348x609mm (13.7x24.0")
    diag: 701mm (27.6") modes: max: 2560x1600 min: 720x400
  Monitor-2: eDP-1 pos: primary,left model: LG res: 1920x1080 hz: 60
    dpi: 142 size: 344x194mm (13.5x7.6") diag: 395mm (15.5") modes: 1920x1080
  OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 22.2.5
    direct render: Yes
Audio:
  Device-1: Intel CM238 HD Audio vendor: Dell driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3 chip-ID: 8086:a171 class-ID: 0403
  Device-2: NVIDIA GP106 High Definition Audio vendor: Dell
    driver: snd_hda_intel v: kernel pcie: speed: 2.5 GT/s lanes: 16
    bus-ID: 01:00.1 chip-ID: 10de:10f1 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-69-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: no
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Dell driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1
    port: d000 bus-ID: 3b:00.0 chip-ID: 10ec:8168 class-ID: 0200
  IF: enp59s0 state: down mac: <filter>
  Device-2: Intel Wi-Fi 6 AX210/AX211/AX411 160MHz driver: iwlwifi
    v: kernel pcie: speed: 5 GT/s lanes: 1 bus-ID: 3c:00.0 chip-ID: 8086:2725
    class-ID: 0280
  IF: wlp60s0 state: up mac: <filter>
  IF-ID-1: tailscale0 state: unknown speed: -1 duplex: full mac: N/A
  IF-ID-2: virbr0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel AX210 Bluetooth type: USB driver: btusb v: 0.8
    bus-ID: 1-4:4 chip-ID: 8087:0032 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 5 state: up address: <filter>
Drives:
  Local Storage: total: 1.84 TiB used: 521.54 GiB (27.7%)
  ID-1: /dev/nvme0n1 vendor: Asgard model: AN3 1TNVMe-M.2 80
    size: 953.87 GiB speed: 31.6 Gb/s lanes: 4 type: SSD serial: <filter>
    rev: 42A2S8MA temp: 37.9 C scheme: GPT
  ID-2: /dev/sda vendor: Seagate model: ST1000LM035-1RK172 size: 931.51 GiB
    speed: 6.0 Gb/s type: HDD rpm: 5400 serial: <filter> rev: SDM2 scheme: GPT
Partition:
  ID-1: / size: 46.63 GiB used: 28.53 GiB (61.2%) fs: ext4
    dev: /dev/nvme0n1p5
  ID-2: /boot size: 983.1 MiB used: 622.7 MiB (63.3%) fs: ext2
    dev: /dev/nvme0n1p4
  ID-3: /boot/efi size: 486 MiB used: 33.8 MiB (7.0%) fs: vfat
    dev: /dev/nvme0n1p1
  ID-4: /home size: 764.5 GiB used: 492.36 GiB (64.4%) fs: ext4
    dev: /dev/nvme0n1p6
Swap:
  ID-1: swap-1 type: partition size: 32 GiB used: 0 KiB (0.0%) priority: -2
    dev: /dev/nvme0n1p7
Sensors:
  System Temperatures: cpu: 53.0 C pch: 58.0 C mobo: 48.0 C sodimm: SODIMM C
  Fan Speeds (RPM): cpu: 4344
Repos:
  Packages: 3209 apt: 3200 flatpak: 9
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/insync.list
    1: deb [signed-by=/usr/share/keyrings/insync.gpg] http://apt.insync.io/mint vera non-free contrib
  Active apt repos in: /etc/apt/sources.list.d/obsproject-obs-studio-jammy.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/obsproject-obs-studio-jammy.gpg] https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https://mint.itsbrasil.net/packages vera main upstream import backport
    2: deb https://ubuntu.itsbrasil.net/ubuntu jammy main restricted universe multiverse
    3: deb https://ubuntu.itsbrasil.net/ubuntu jammy-updates main restricted universe multiverse
    4: deb https://ubuntu.itsbrasil.net/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/spotify.list
    1: deb [signed-by=/usr/share/keyrings/spotify.gpg] http://repository.spotify.com stable non-free
  Active apt repos in: /etc/apt/sources.list.d/tailscale.list
    1: deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https://repo.vivaldi.com/stable/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [signed-by=/usr/share/keyrings/vscode.gpg arch=amd64] https://packages.microsoft.com/repos/code stable main
  Active apt repos in: /etc/apt/sources.list.d/wine.list
    1: deb [signed-by=/usr/share/keyrings/wine.gpg] https://dl.winehq.org/wine-builds/ubuntu/ jammy main
Info:
  Processes: 388 Uptime: 22h 53m wakeups: 33 Memory: 31.22 GiB
  used: 8.12 GiB (26.0%) Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.3.0 alt: 11/12 Shell: Zsh v: 5.8.1 running-in: gnome-terminal
  inxi: 3.3.13
```

**Comment by jthomaschewski** [comment] 2023-04-02 13:58
Thank you for the report. I was able to reproduce the issue as described.

It appears that Cinnamon has updated its underlying D-Bus service, which is utilized by Display Settings. The new implementation relies on a service provided by "Muffin", the Cinnamon window manager.

Unfortunately, a fix is not straithforward because "Muffin" is not loaded in the i3-cinnamon configuration. All window management is handled by i3. This problem is also present in configurations such as `i3-gnome` and others.

I will close this issue as I do not plan to fix it and do not believe it is feasible at the moment. However, if anyone is willing to work on this, please feel free to comment, reopen, or submit a PR.

In the meantime, consider using alternative tools like https://github.com/phillipberndt/autorandr (Automatic config) and https://github.com/haad/arandr (GUI-based, one-time config).

### Details

Upon opening Cinnamon Display Settings, an error is logged indicating that the `org.cinnamon.Muffin.DisplayConfig` dbus service is non-existent:
```console
** (cinnamon-settings.py:1634450): WARNING **: 15:25:06.684: Error calling GetCurrentState: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.cinnamon.Muffin.DisplayConfig" does not exist
```

This change appears to have been introduced in either Cinnamon `v5.3` or `v5.4`. These versions include a merge of a more recent Gnome Mutter version and updates to the Cinnamon Control Center.  
Potentially relevant commit: https://github.com/linuxmint/cinnamon-control-center/commit/1700e782731691f54d22a7f6b59bd851bfa54605#diff-e1991130c5e25d082b2886be828164efa43a5145b6288247f2517769e84bd2a0

**Closed by jthomaschewski** 2023-04-02 13:58 UTC
